#!/usr/bin/env bash
# One-time environment setup on HPC2 (Orion). Run once from a login node
# (needs internet to pip install) -- not part of any sbatch job.
#
# This project is flat scripts + `requests`, not an installable package
# (unlike fair_ocean_agent), so this is much lighter than that project's
# setup_env.sh: one conda env with requests (CPU-side) and, only in that
# same env, vllm (GPU-side uses the same env for simplicity).
#
# Usage:
#   git clone <this-repo-url> genetic_tractability
#   cd genetic_tractability
#   CONDA_ENV_PREFIX=/scratch/$USER/conda_envs/genetic-tractability ./cluster/setup_env.sh
#
# If $HOME has a small quota (common on HPC -- vllm pulls in torch + CUDA
# libraries, easily several GB), always use CONDA_ENV_PREFIX to put the env
# (and pip's cache) on scratch space instead of the default $HOME/miniforge3.
set -euo pipefail

cd "$(dirname "$0")/.."   # repo root (genetic_tractability/)

CONDA_ENV_NAME="${CONDA_ENV_NAME:-genetic-tractability}"
CONDA_ENV_PREFIX="${CONDA_ENV_PREFIX:-}"
PYTHON_VERSION="${PYTHON_VERSION:-3.11}"
MINIFORGE_HOME="${MINIFORGE_HOME:-$HOME/miniforge3}"
CONDA_SH="${MINIFORGE_HOME}/etc/profile.d/conda.sh"

if [ ! -f "${CONDA_SH}" ]; then
  echo "conda.sh not found at ${CONDA_SH}." >&2
  echo "Set MINIFORGE_HOME if your (mini)conda/anaconda install lives elsewhere." >&2
  exit 2
fi
# shellcheck source=/dev/null
source "${CONDA_SH}"

if [ -n "${CONDA_ENV_PREFIX}" ]; then
  CONDA_TARGET="${CONDA_ENV_PREFIX}"
  CONDA_CREATE_FLAG=(-p "${CONDA_ENV_PREFIX}")
  # Same quota trap fair_ocean_agent's setup_env.sh documents: conda's own
  # package cache and pip's build cache both default under $HOME
  # independently of where the env itself lives.
  export PIP_CACHE_DIR="${PIP_CACHE_DIR:-$(dirname "${CONDA_ENV_PREFIX}")/pip_cache}"
  export CONDA_PKGS_DIRS="${CONDA_PKGS_DIRS:-$(dirname "${CONDA_ENV_PREFIX}")/conda_pkgs}"
  mkdir -p "${PIP_CACHE_DIR}" "${CONDA_PKGS_DIRS}"
else
  CONDA_TARGET="${CONDA_ENV_NAME}"
  CONDA_CREATE_FLAG=(-n "${CONDA_ENV_NAME}")
fi

if { [ -n "${CONDA_ENV_PREFIX}" ] && [ -x "${CONDA_ENV_PREFIX}/bin/python" ]; } || \
   { [ -z "${CONDA_ENV_PREFIX}" ] && conda env list | awk '{print $1}' | grep -qx "${CONDA_ENV_NAME}"; }; then
  echo "conda env '${CONDA_TARGET}' already exists, reusing it."
else
  echo "Creating conda env at '${CONDA_TARGET}' (python=${PYTHON_VERSION})..."
  conda create "${CONDA_CREATE_FLAG[@]}" "python=${PYTHON_VERSION}" -y
fi
conda activate "${CONDA_TARGET}"

ACTUAL_PREFIX="$(python -c 'import sys; print(sys.prefix)')"
EXPECTED_PREFIX="${CONDA_ENV_PREFIX:-$(conda env list | awk -v n="${CONDA_ENV_NAME}" '$1==n {print $NF}')}"
if [ "${ACTUAL_PREFIX}" != "${EXPECTED_PREFIX}" ]; then
  echo "conda activate did not take effect (expected ${EXPECTED_PREFIX}, got ${ACTUAL_PREFIX})." >&2
  echo "Check for a shell-profile-activated virtualenv/conda env overriding it." >&2
  exit 2
fi
echo "Python: $(python --version) (${ACTUAL_PREFIX})"

pip install --upgrade pip
pip install -r cluster/requirements.txt

cat > cluster/env_activate.sh <<EOF
# Auto-generated by setup_env.sh -- do not edit by hand, re-run setup_env.sh instead.
source "${CONDA_SH}"
conda activate "${CONDA_TARGET}"
$([ -n "${CONDA_ENV_PREFIX}" ] && echo "export PIP_CACHE_DIR=\"${PIP_CACHE_DIR}\"")
$([ -n "${CONDA_ENV_PREFIX}" ] && echo "export CONDA_PKGS_DIRS=\"${CONDA_PKGS_DIRS}\"")
EOF

echo
echo "Base environment ready. Next steps:"
echo "  1. For the GPU/vLLM stage: pip install vllm (and flashinfer-python>=0.6.16.post4"
echo "     -- see cluster/README.md for why) in this SAME env, from a node with internet."
echo "  2. Download the model once: ./cluster/download_vllm_model.sh"
echo "  3. Submit cluster/run_discovery.sbatch, then cluster/run_prefetch.sbatch,"
echo "     then cluster/run_extraction.sbatch, then cluster/run_genome_matching.sbatch."
echo
echo "Quick self-test (no network, no LLM):"
echo "  source cluster/env_activate.sh && python -c \"import sys; sys.path.insert(0,'scripts'); import keyword_lexicon, text_sections; print('imports OK')\""
